### ISSUE TITLE
Curate issues labelled with `hacktoberfest` label during the Hacktoberfest

### ISSUE THREAD

**Issue by siddhant-deepsource** [DeepSourceCorp/good-first-issue#314]
Since hacktoberfest is going to start soon, it will be really helpful for the beginners if they can find all the `hacktoberfest` labelled issues as well on gfi. 

We can however add a certain mark (maybe a star or a label next to the issue title as Github does) which can help them differentiate issues labelled as `hacktoberfest` from the ones labelled as `good-first-issue`.

**Comment by tejassinghsital** [comment]
Hi, I want to contribute my good first issue but don't really know how to do it. Can you assign this one to me? I don't know much about contributing but will try my best...

**Comment by varsha080** [comment]
Hyee..can you assign this issue to me. I'll try my best to fix it

**Comment by Prathamesh-Dukare** [comment]
Hey I would Love to do this

**Comment by jai-deepsource** [comment]
Please send a PR with updating the labels here - https://github.com/deepsourcelabs/good-first-issue/blob/master/data/labels.json

**Comment by Dinakar04** [comment]
hi can someone tell how to contribute for this issue

**Comment by Kannan0017** [comment]
Hi there, I would like to fix this issue.

**Comment by lucavallin** [comment]
Hey @siddhant-deepsource @tejassinghsital @varsha080 @enigmacoder-bot @Prathamesh-Dukare @jai-deepsource @Dinakar04 @Prathamesh-Dukare @Kannan0017 ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request or an issue there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Comment by Deeparawat** [comment]
Hey admin , please assign this to me i will fix it.
