### ISSUE TITLE
sw.js

### ISSUE THREAD

**Issue by p4nu** [DeepSourceCorp/good-first-issue#422]
This can be ignored as it should not be version controlled.

I'll make a PR about this.

**Comment by lucavallin** [comment]
Hey @p4nu! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request or an issue there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Comment by sanket-deepsource** [comment]
Thanks @p4nu. This has been fixed (and the app has been upgraded to use Nuxt 3).
