### ISSUE TITLE
Added Dev Interview Helper app

### ISSUE THREAD

**Issue by Tc2r1** [DeepSourceCorp/good-first-issue#508]
#507

**Comment by lucavallin** [comment]
Hey @Tc2r1    ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request or an issue there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.
