### ISSUE TITLE
create a discord channel

### ISSUE THREAD

**Issue by Sajiyah-Salat** [DeepSourceCorp/good-first-issue#520]
I want to add my project to this repository but I am not an experienced person So I need other people's help. Sorry to say but your contribution guide is not beginner friendly.

**Comment by Strik3ria** [comment]
@Sajiyah-Salat At a glance it looks like you need to answer four questions about requirements, then add your  project to the [data/repositories.toml](https://github.com/deepsourcelabs/good-first-issue/blob/master/data/repositories.toml) and create a pull request to be approved my the maintainers of this project. 

Those four questions are:
Question 1: Does your project meet this? -> It has at least three issues with the good first issue label. This label is already present on all repositories by default. If not, you can follow the steps [here](https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests).

Question 2: Does your project meet this? -> It has at least 10 contributors.

Question 3: Does your project meet this? -> It contains a README.md with detailed setup instructions for the project, and a CONTRIBUTING.md with guidelines for new contributors.

Question 4: Does your project meet this? -> It is actively maintained.

**Comment by lucavallin** [comment]
Hey @Sajiyah-Salat and @Strik3ria   ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request or an issue there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.
