### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by silverrres** [DeepSourceCorp/good-first-issue#524]
i have problem with a bug about the set rotation method in the matrix4

![Capture](https://user-images.githubusercontent.com/118355736/202202072-06967747-9f43-48a1-8d4c-594cd00e9f32.PNG)

**Comment by Donhuttan123** [comment]
To avoid this bug, you passed this parameter when using it, but an error will be prompted in ts
![image](https://user-images.githubusercontent.com/118355736/202202819-d921baed-b67b-4c76-ac39-2bc01048134c.png)
![image](https://user-images.githubusercontent.com/118355736/202202887-028266e0-599b-4449-a97d-6f18398b3efd.png)

So to fix it you added this parameter to the source code

![image](https://user-images.githubusercontent.com/118355736/202203001-249d2f4d-0a59-4b3e-bab5-128ee98527ef.png)

After this you should have no problem when run the code matrix

![image](https://user-images.githubusercontent.com/113320758/202204268-a97c1fa9-e73b-411e-9a27-80396b2e732a.png)

**Comment by lucavallin** [comment]
Hey @silverrres and @Donhuttan123 ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request or an issue there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Comment by shirsho-roy** [comment]
I would like to work on this issue. Could someone guide me?

**Comment by Williamehanksjr** [comment]
I can't be much off a guide as I am retired engineer wanting to get back in the game. The first step would be to reproduce the problem.
