### ISSUE TITLE
What is Algolia used for?

### ISSUE THREAD

**Issue by lucavallin** [DeepSourceCorp/good-first-issue#535]
Hello, I noticed this project is a little unmaintained, therefore I forked it at https://github.com/lucavallin/gfi and I am planning to revamp it a little.
I don't understand how Algolia is used however. In the file https://github.com/deepsourcelabs/good-first-issue/blob/master/gfi/index.py, the script is using Algolia to "index" something. What is it doing exactly, and why is that?

Thanks

**Comment by sahil-MK2** [comment]
hey i would like to work on this issue, please assign me this issue

**Comment by lucavallin** [comment]
@sahil-MK2 Unfortunately I don't have permissions to do so. If you'd like to collaborate on https://github.com/lucavallin/gfi, however, I can give you access there.

**Comment by lucavallin** [comment]
Hey @sahil-MK2  ! I tried to contribute to this repo as well but I haven't seen any activity in the last few months. I decided to fork it to keep it alive. Please see https://github.com/lucavallin/gfi and feel free to open a pull request or an issue there. At this time I am setting up the hosting and cleaning up the code. If you're up for it, I could use some help to convert the app from Nuxt.js & Python to Next.js & Typescript.

**Comment by TakasiVenkataSandeep-08** [comment]
Hi @lucavallin how can we get in touch I'm intrested in contributing to your project

**Comment by lucavallin** [comment]
Hey @TakasiVenkataSandeep-08, sure, great to hear! Feel free to open a discussion on my fork and we can have a chat there :)

**Comment by sudhanshuhunny** [comment]
Hi Is @TakasiVenkataSandeep-08  are you working on this ?
