### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED while starting the development server.

### ISSUE THREAD

**Issue by prathamjagga** [DeepSourceCorp/good-first-issue#542]
I am encountering the following error when I start the dev server using "yarn dev -o" command:
![Screenshot from 2022-12-25 22-53-53](https://user-images.githubusercontent.com/30550632/209476987-f8455811-9f47-4713-9a22-b34adfc94959.png)
Node Version: 18.12.1 LTS
Ubuntu Version: Ubuntu 20.04.5 LTS

**Comment by ftkovr9k** [comment]
There is a work-around with export NODE_OPTIONS=--openssl-legacy-provider. You don't have to downgrade Node.

**Comment by ladislauNagy** [comment]
> There is a work-around with export NODE_OPTIONS=--openssl-legacy-provider. You don't have to downgrade Node.

The issue still reproduces.

**Comment by sanket-deepsource** [comment]
Hi! This has been fixed. Please use Node 20 with bun and it should work as expected.
