### ISSUE TITLE
Sync and Update problem

### ISSUE THREAD

**Issue by adilaxmdv** [DeepSourceCorp/good-first-issue#559]
![image](https://user-images.githubusercontent.com/74068841/222985056-9c68377f-fb14-4eff-9214-b73c177543bf.png)

![image](https://user-images.githubusercontent.com/74068841/222985070-c67db820-129b-4dbd-b44c-435dff2dab3d.png)

Website is not sync with repo in my mind

**Comment by HoneyTyagii** [comment]
hello @adilaxmdv To resolve this, I suggest checking if there are any changes that need to be pulled from the repository to your local website. You can do this by running the "git pull" command in the command line while in the local repository directory. Once you've pulled the changes, you can update your website by rebuilding it with the updated content. If you're still having issues after trying these steps, please let us know and we'll work together to find a solution.

**Comment by adilaxmdv** [comment]
I dont make any changes just I make this issue for bug . Anyone will debug it

**Comment by HoneyTyagii** [comment]
Fortunately, I'm not encountering the same issue at the moment.

**Comment by adilaxmdv** [comment]
https://goodfirstissue.dev/language/python look here  example 
![image](https://user-images.githubusercontent.com/74068841/223186027-6c1d016e-2773-46c1-80c8-63d20cb5e8c5.png)

but
![image](https://user-images.githubusercontent.com/74068841/223186063-ee018c91-3c15-4b47-aa44-81a59ee0a432.png)

I say that

**Comment by michael-dez** [comment]
@HoneyTyagii I believe @adilaxmdv is saying that the 'last activity' field seems to show a minimum of 2 months, even when there has been more recent activity on a project. I just noticed this happening [here](https://goodfirstissue.dev/language/go) then found an existing issue.

**Comment by adilaxmdv** [comment]
@michael-dez yes I say that

**Comment by Mustafiz04** [comment]
Hey, 
Is anyone working on this ? or can I pick up this task?

**Comment by adilaxmdv** [comment]
@Mustafiz04 anyone not working you can take task

**Comment by Mustafiz04** [comment]
Sure, thanks.
I will update here soon.

**Comment by Mustafiz04** [comment]
Hey, I have raised the PR for this issue.
Can you please review this and merge it?

<img width="1672" alt="Screenshot 2023-03-09 at 10 45 18 PM" src="https://user-images.githubusercontent.com/49086821/224104376-2734dd18-b6d5-45b7-8dd9-b1bf6af7f536.png">


https://github.com/deepsourcelabs/good-first-issue/pull/564#issue-1617637119

**Comment by Mustafiz04** [comment]
How can I fix that? I am not able to understand what is the issue there.
@adilaxmdv

**Comment by adilaxmdv** [comment]
must authorized man look at this

**Comment by Mustafiz04** [comment]
Man, I am getting this by clicking (Inspect) Can you please help me how to resolve this?

<img width="1674" alt="Screenshot 2023-03-09 at 11 19 33 PM" src="https://user-images.githubusercontent.com/49086821/224112676-c0f02d64-9f24-45da-a441-1c2c5801e0da.png">

**Comment by adilaxmdv** [comment]
@Mustafiz04 I dont know what is problem

**Comment by Mustafiz04** [comment]
🥲

**Comment by Mustafiz04** [comment]
can someone else help with this?

**Comment by sanket-deepsource** [comment]
Hi! This should be fixed with the latest release. Thanks!
