### ISSUE TITLE
Added juspay/hyperswitch

### ISSUE THREAD

**Issue by manojradhakrishnan** [DeepSourceCorp/good-first-issue#579]
Adding juspay/hyperswitch - An Open Source Financial Switch to make Payments fast, reliable and affordable

**Comment by MehmetTerc** [comment]
Can you describe me the issue clearer ? @manojradhakrishnan

**Comment by manojradhakrishnan** [comment]
@MehmetTerc Adding an open source project for which I am a maintainer. The project is actively maintained and had good first issue for new contributors. 

Please add it to the collection.

**Comment by manojradhakrishnan** [comment]
Link to pull request #581
