### ISSUE TITLE
chore: add projectshut open source project 

### ISSUE THREAD

**Issue by priyankarpal** [DeepSourceCorp/good-first-issue#587]
I want to add projectshut open source project. 

### What is ProjectsHut?
- Projectshut is an open-source web app that enables users to freely publish their projects and create user profiles within the platform. 

### Repository URL
https://github.com/priyankarpal/ProjectsHut

**Comment by CedricNdong** [comment]
i dont understand your issue

**Comment by priyankarpal** [comment]
I mean I want to add my repository for good-first-issue
