### ISSUE TITLE
chore: Add Free-Hit 

### ISSUE THREAD

**Issue by JasonDsouza212** [DeepSourceCorp/good-first-issue#605]
I am planning to add **Free-Hit** to **good-first-issue** .
Free-Hit is an application that is used to search for Free tools that are both free and helpful for our needs.

**Application link:** https://free-hit.vercel.app/

**Repo link:** https://github.com/JasonDsouza212/free-hit

**Comment by Vaishali054** [comment]
Is this issue still open, I would like to work on this.
