### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by surfiniaburger** [DeepSourceCorp/good-first-issue#632]
## Description
As I read through the README file I discovered a typo.

## Expected Behavior
It should be "Next.js"

## Actual Behavior
What is written is "Nuxt.js"

## How to reproduce

1. Scroll down to the README.md page on https://github.com/DeepSourceCorp/good-first-issue
2. At the last section "Setting up your project locally"
3.  The first line shows the text that contains the typo

## Screenshots
![Screenshot (177)](https://github.com/DeepSourceCorp/good-first-issue/assets/102007621/7bb322fa-c68f-4fa2-a53d-f6f34ad21cae)

## Suggestion
Replace the affected word in the text with "Next.js".

**Comment by surfiniaburger** [comment]
Admin! Please can I take this issue

**Comment by Shishirr17** [comment]
hey i would love to solve the issue 
can u assign this to me !

**Comment by Abdulfattah1001** [comment]
Good day Admin 👋, please I would like to solve this issue🙏🙏

**Comment by JehanPatel** [comment]
Hey Admin! I would like to contribute!

**Comment by geethdev** [comment]
Hey! I would like to contribute!

**Comment by Shx-v** [comment]
Admins! I would like to solve this issue

**Comment by ritik-sri** [comment]
I would like to solve this issue

**Comment by git-akshay-jadhav** [comment]
Could you please assign this issue to me

**Comment by Deeparawat** [comment]
Hey admin! Could you please assign me this issue i can fix this quickly

**Comment by NarThmpsn** [comment]
Hey I would love to work on this!

**Comment by sanket-deepsource** [comment]
Hi! This project uses [Nuxt.js](https://nuxt.com/). This is not a typo.
