### ISSUE TITLE
TRACK_MOBILE_PHONE

### ISSUE THREAD

**Issue by paulsuryanshu** [DeepSourceCorp/good-first-issue#643]
THIS CAN TRACK MOBILE PHONE....

**Comment by Anshu370** [comment]
Sir, pls Elaborate the problem.
let me try to solve this.

**Comment by paulsuryanshu** [comment]
the problem is to write a program which can detect the basic sim location and operator

**Comment by Anshu370** [comment]
Ya i can Create this using Python.
You can check my GitHub repos.
