### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by guibranco** [DeepSourceCorp/good-first-issue#646]
There have been many pull requests and issues open for a long time, and the last commit was in December 2022, almost a year ago...

So my question is: is anyone working on this repository still or has it been abandoned?

**Comment by shiwanhs05** [comment]
+1

**Comment by aqeelat** [comment]
Probably not, but there's a maintained fork:

https://github.com/lucavallin/first-issue

**Comment by EmmanuelPallares** [comment]
+2

**Comment by MrAshwin2142** [comment]
+3

**Comment by sanket-deepsource** [comment]
Hey there! I know this project has been unmaintained for quite some time — apologies! We see there's quite a backlog and we're working on it. Please allow us some time and we'll merge the PRs. Thanks!
