### ISSUE TITLE
error: postinstall script from "nuxt-app" exited with 1

### ISSUE THREAD

**Issue by jonasermert** [DeepSourceCorp/good-first-issue#692]
Hello,

I wanted to install the app via bun, and I've got the following error:

`_bun install v1.0.21 (837cbd60)
  ⚙️  nuxt-app [5/5] [nuxt:tailwindcss] ℹ Using default Tailwind CSS file

 ERROR  Named export 'execa' not found. The requested module 'execa' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'execa';
const { execa } = pkg;

  import { execa } from 'execa';
  ^^^^^
  SyntaxError: Named export 'execa' not found. The requested module 'execa' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'execa';
  const { execa } = pkg;
  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) 

 ERROR  Named export 'execa' not found. The requested module 'execa' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'execa';
const { execa } = pkg;

error: postinstall script from "nuxt-app" exited with 1_`

![error](https://github.com/DeepSourceCorp/good-first-issue/assets/1409808/ef5602ea-5a4f-42fc-8821-ff9feb265930)

Can anyone help me? Thanks in advance.

**Comment by sanket-deepsource** [comment]
@jonasermert What's the node version you're using?

**Comment by jonasermert** [comment]
> @jonasermert What's the node version you're using?

v18.16.1

**Comment by jonasermert** [comment]
Hello, 

here is an update: 
I've updated my Node version to v21.6.0. Now, the bun installation works fine.

![buninstall](https://github.com/DeepSourceCorp/good-first-issue/assets/1409808/6901cc40-6656-40da-bd0a-4fbdb306ce07)

Start the bun dev works, too.

![terminalbundev](https://github.com/DeepSourceCorp/good-first-issue/assets/1409808/5129c27f-52b5-4be1-b3f7-c99d3528b568)

And I can open the localhost, now.

![localhost](https://github.com/DeepSourceCorp/good-first-issue/assets/1409808/78e0ad0e-567e-4b9c-9a55-7d4a9ad1540e)

Maybe, the version was the problem...
