### ISSUE TITLE
Cannot Get Checks To Pass

### ISSUE THREAD

**Issue by alexsherstinsky** [DeepSourceCorp/good-first-issue#718]
Hello, I submitted the pull request [proposing two new open source libraries to be added to the list](https://github.com/DeepSourceCorp/good-first-issue/pull/717), but it is failing checks, and I do not know what I should do next.  Please help.  Thank you very much.

**Comment by rudransh61** [comment]
Same problem brother ??
#720

**Comment by alexsherstinsky** [comment]
@rudransh61 Yes -- did you get any help?  I have not heard back from anybody yet, so not even sure what I should do.  Thank you very much.

**Comment by rudransh61** [comment]
pls can you help me

**Comment by sanket-deepsource** [comment]
The Vercel check is no longer required for merge.

**Comment by alexsherstinsky** [comment]
@sanket-deepsource You closed this issue, but [my pull request](https://github.com/DeepSourceCorp/good-first-issue/issues/718#issue-2163729163) is still not in a mergeable state, because Vercel checks are failing, and no one has approved it.  Could you please help me by telling me what I should do next?  Thank you very much.
